import Head from "next/head";
import { Inter } from "next/font/google";
// import styles from '@/styles/Home.module.css'
import { Paper, Container, Typography, Box, Button } from "@mui/material";
import Header from "@/components/header/Header";
import HeaderMenu from "@/components/menu/topMenu/HeaderMenu";
import ProposalCard from "@/components/ProposalCard/ProposalCard";
// import OfferCards from "@/components/ProposalCard/OfferCards";
import {useState} from "react"  
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  interface offerStructure {
    id : number
    cost : number
    users : number
    storage : string
    support : string
    action : string

}
    const [Offer, setOffer] = useState<offerStructure[]>([
    {id : 1 , cost : 0 , users : 10 , storage : "2 GB" , support : "Email" , action : "SIGN UP FOR FREE"},
    {id : 2 , cost : 15 , users : 20 , storage : "10 GB" , support : "Priority email", action : "GET STARTED"},
    {id : 3 , cost : 30 , users : 50 , storage : "30 GB" , support : "Phone & email" , action : "CONTACT US"},
    
])

const finalOffers = Offer.map((value)=>{
return(
    <ProposalCard
    cost={value.cost}
    users={value.users}
    storage={value.storage}
    support={value.support}
    action={value.action}
   
    />
)
})
  return (
    <>
      <Head>
        <title>first UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}>
              </main> */}

      <Header title={"COMANY NAME"}>
        <HeaderMenu />
      </Header>
      <Container
        sx={{
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <Typography variant="h3" sx={{ mt: 5 }}>
          Pricing
        </Typography>
        <Box sx={{ maxWidth: "250px", width: "70%" }}>
          <Typography variant="subtitle1">
            Quickly build an effective pricing table for your potential
            customers with this layout. It's built with default MUI components
            with little customization.
          </Typography>
        </Box>
        <Box sx={{display:"flex" , justifyContent : " space-evenly" ,width : "75%" , minWidth:"300px" , flexWrap:"wrap" , mt:5}}>
        {finalOffers}
        </Box>
        
       <Footer/>
      </Container>
    </>
  );

}